cache_path: "wdir/pm25_california/cache.pkl"
weights_path: "wdir/pm25_california/weights.pkl"
label: PM2.5
aoi: California
indim: 7
outdim: 1

feature_keys: [
    "pm25_native", "pm25_target", 
    "no2_surface_native", "no2_surface_target",
    'modis_diff',
    'elevation_native', 'elevation_target',
]

models: 
    model1: 
        sizes: [32, 32]
        lr: 0.00001
        epochs: 1024
        batch_size: 32
        dropout: 0.15
        use_swish: False
        use_batch_norm: False
        patience: 30

    model2: 
        sizes: [32, 32]
        lr: 0.00002
        epochs: 2048
        batch_size: 64
        dropout: 0.1
        use_swish: False
        use_batch_norm: False
        patience: 30

    model3: 
        sizes: [32, 32]
        lr: 0.00003
        epochs: 2048
        batch_size: 128
        dropout: 0.1
        use_swish: False
        use_batch_norm: False
        patience: 30

    model4: 
        sizes: [32, 32]
        lr: 0.00002
        epochs: 2048
        batch_size: 64
        dropout: 0.15
        use_swish: False
        use_batch_norm: False
        patience: 30

